$('.owl-carousel').owlCarousel({
    loop:true,
    margin:5,
    autoplay:true,
    autoplayTimeout:1000,
    autoplayHoverPause:true,
    dots:true,

    nav:false,
    responsive:{
        0:{
            items:2
        },
        600:{
            items:4
        },
        1000:{
            items:6
        }
    }
})
